version: '3.8'

services:
  fogos.server:
    image: nginx:1.21.0
    expose:
      - 80
    volumes:
      - ./.docker/server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/server/conf.d:/etc/nginx/conf.d:ro
      - .:/var/www/html:delegated
    restart: unless-stopped
    networks:
      fogos:
        aliases:
          - api.fogos.pt

  fogos.api:
    image: docker.pkg.github.com/fogospt/fogosapi/php:8.0-fpm-prod
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    depends_on:
      - fogos.mongodb
    networks:
      - fogos

  fogos.mongodb:
    image: mongo:4.4.6
    expose:
      - 27017
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - ./.docker/mongodb/timezone:/etc/timezone
      - ./.docker/mongodb/localtime:/etc/localtime
    networks:
      - fogos

  fogos.redis:
    image: redis:6.2.3-alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - fogos

  fogos.chrome:
    image: 'zenika/alpine-chrome:81'
    entrypoint: [ "chromium-browser", "--headless", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
    expose:
      - 9222
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2048M
    networks:
      - fogos

  fogos.scheduler:
    image: docker.pkg.github.com/fogospt/fogosapi/scheduler
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./.docker/scheduler/cron.d:/etc/cron.d
    expose:
      - 9000
    depends_on:
      - fogos.api
    networks:
      - fogos
    entrypoint: ./.docker/scheduler/entrypoint.sh

volumes:
  mongodb_data:

networks:
  fogos:
    name: fogos-api
