name: "Run tests"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .docker/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - .docker/**

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    name: For PHP ${{ matrix.php }}

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mongodb
          coverage: pcov

      - name: Duplicate example env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --testdox --coverage-clover build/logs/clover.xml
        env:
          DB_HOST: localhost
